### PR TITLE
Use cmake version compare to determine HASGAINS

### LINKED ISSUE #24: Gains disabled incorrectly by version detection
The current libairspyhf is v1.7.1. This code
https://github.com/pothosware/SoapyAirspyHF/blob/d6825331a6bfc3578dc6fe5091fce3d550b6af3c/Settings.cpp#L29
detects that as being too old to define `HASGAINS`, so several parameters are disabled.

### PR DESCRIPTION
**Pull request by willcode**
Fixes #24

### CODE REVIEW

**Comment by willcode** [comment]
@guruofquality @ncorgan Any comments on this one?

**Comment by guruofquality** [comment]
> @guruofquality @ncorgan Any comments on this one?

my worry is that many time package config files arent present and PC_LIBAIRSPYHF_VERSION wont be set.

I think letting cmake check for `airspyhf_set_hf_att` with https://cmake.org/cmake/help/latest/module/CheckFunctionExists.html with `check_function_exists` to set `HASGAINS`  may be more robust

**Comment by willcode** [comment]
@guruofquality changed to use `check_function_exists`.

**Comment by guruofquality** [comment]
nice thanks

**Pull request merged**
